version: '3.3'
services:
  app:
    container_name: openweather-nestjs
    image: openweather-nestjs:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
  db:
    image: mongo:latest
    ports: 
      - 27017:27017